import { useState } from 'react'
import { useI18n } from '../../app/i18n'
import { loadVersion } from '../../data/client'
import { saveFormationPreset } from '../../data/formationPresetStore'
import { PRESET_SCHEMA_VERSION } from '../formation/types'
import type { PlannerResult } from '../../domain/planner/recommendationTypes'
import type { FormationPreset, ScenarioRef } from '../../domain/types/formation'

interface PlannerSavePresetProps {
  result: PlannerResult | null
  layoutId: string | null
  scenarioRef: ScenarioRef | null
}

export function PlannerSavePreset({ result, layoutId, scenarioRef }: PlannerSavePresetProps) {
  const { t } = useI18n()
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  if (!result || !layoutId) {
    return (
      <section className="surface-card planner-save-preset" aria-label={t({ zh: '结果保存', en: 'Result save' })}>
        <div className="surface-card__body planner-save-preset__body">
          <div className="planner-save-preset__copy">
            <strong>{t({ zh: '尚无可保存方案', en: 'No savable preset yet' })}</strong>
            <p>{t({ zh: '先让 planner 生成一条合法推荐，再把结果存进方案存档。', en: 'Generate a legal recommendation before saving it as a preset.' })}</p>
          </div>
          <button type="button" className="action-button" disabled>{t({ zh: '保存', en: 'Save' })}</button>
        </div>
      </section>
    )
  }

  const presetResult = result
  const presetLayoutId = layoutId

  async function handleSave() {
    setSaving(true)
    setError(null)

    try {
      const now = new Date().toISOString()
      const { current: dataVersion } = await loadVersion()
      const preset: FormationPreset = {
        id: `planner-${Date.now()}`,
        schemaVersion: PRESET_SCHEMA_VERSION,
        dataVersion,
        name: t({ zh: '自动计划推荐', en: 'Planner recommendation' }),
        description: t({
          zh: `自动计划生成，评分 ${presetResult.score}`,
          en: `Generated by planner with score ${presetResult.score}`,
        }),
        layoutId: presetLayoutId,
        placements: presetResult.placements,
        scenarioRef,
        scenarioTags: scenarioRef ? [`${scenarioRef.kind}:${scenarioRef.id}`] : [],
        priority: 'medium',
        createdAt: now,
        updatedAt: now,
      }

      await saveFormationPreset(preset)
      setSaved(true)
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught))
    } finally {
      setSaving(false)
    }
  }

  return (
    <section className="surface-card planner-save-preset" aria-label={t({ zh: '结果保存', en: 'Result save' })}>
      <div className="surface-card__body planner-save-preset__body">
        <div className="planner-save-preset__copy">
          <strong>{t({ zh: '把当前推荐写入方案存档', en: 'Store the current recommendation as a preset' })}</strong>
          <p>{t({ zh: '保存后可回到“方案存档”继续编辑或覆盖命名方案。', en: 'After saving, continue editing or rename it from the Presets page.' })}</p>
          {saved ? <span className="planner-save-preset__status">{t({ zh: '已保存', en: 'Saved' })}</span> : null}
          {error ? <span className="planner-save-preset__status" role="alert">{error}</span> : null}
        </div>
        <button
          type="button"
          className="action-button action-button--secondary"
          onClick={() => void handleSave()}
          disabled={saving || saved}
        >
          {saving ? t({ zh: '保存中', en: 'Saving' }) : t({ zh: '保存', en: 'Save' })}
        </button>
      </div>
    </section>
  )
}
