import { useState } from 'react'
import { useI18n } from '../../app/i18n'
import { saveFormationPreset } from '../../data/formationPresetStore'
import type { FormationPreset, ScenarioRef } from '../../domain/types/formation'

interface PlannerResult {
  score: string
  placements: Record<string, string>
  explanations: string[]
  warnings: string[]
}

interface PlannerSavePresetProps {
  result: PlannerResult | null
  layoutId: string | null
  scenarioRef: ScenarioRef | null
}

export function PlannerSavePreset({ result, layoutId, scenarioRef }: PlannerSavePresetProps) {
  const { t } = useI18n()
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  if (!result || !layoutId) {
    return (
      <div>
        <button type="button" disabled>{t({ zh: '保存', en: 'Save' })}</button>
      </div>
    )
  }

  const presetResult = result
  const presetLayoutId = layoutId

  async function handleSave() {
    setSaving(true)
    setError(null)

    try {
      const now = new Date().toISOString()
      const preset: FormationPreset = {
        id: `planner-${Date.now()}`,
        schemaVersion: 1,
        dataVersion: 'planner-local',
        name: t({ zh: '自动计划推荐', en: 'Planner recommendation' }),
        description: t({
          zh: `自动计划生成，评分 ${presetResult.score}`,
          en: `Generated by planner with score ${presetResult.score}`,
        }),
        layoutId: presetLayoutId,
        placements: presetResult.placements,
        scenarioRef,
        scenarioTags: scenarioRef ? [`${scenarioRef.kind}:${scenarioRef.id}`] : [],
        priority: 'medium',
        createdAt: now,
        updatedAt: now,
      }

      await saveFormationPreset(preset)
      setSaved(true)
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught))
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <button type="button" onClick={() => void handleSave()} disabled={saving || saved}>
        {saving ? t({ zh: '保存中', en: 'Saving' }) : t({ zh: '保存', en: 'Save' })}
      </button>
      {saved && <span>{t({ zh: '已保存', en: 'Saved' })}</span>}
      {error && <span role="alert">{error}</span>}
    </div>
  )
}
